### ISSUE TITLE
Bug: deploying a service catalog product that has a CommaDelimitedList and AllowedPattern fails

### ISSUE THREAD

**Issue by angold5** [aws-cloudformation/aws-cloudformation-resource-providers-servicecatalog#10]
Im trying to deploy a Service Catalog Product that has been shared with my AWS account.

```
  AWSOrganizationId:
    Description: "Comma-separated IDs of AWS Organizations where this account and the target pipeline account are members."
    Type: "CommaDelimitedList"
    Default: "o-sdfdfdggg,o-dfgfdgdgdfg"
    AllowedPattern: "^[a-z0-9-]+$"
    ConstraintDescription: "must be a valid organization ID, made of lowercase letters and numbers"
```

The above works fine if I deploy it as a normal Cloudformation. 

If I try deploy it as a Product in Service Catalog thats been shared with me, it errors. It seems that when launched via a Product, the regex no longer works with "CommaDelimitedList" and doesnt like the comma.

```
AWSOrganizationId
Comma-separated IDs of AWS Organizations where this account and the target pipeline account are members
Must match pattern: ^[a-z0-9-]+$
```

https://docs.aws.amazon.com/AWSCloudFormation/latest/UserGuide/parameters-section-structure.html#parameters-section-structure-properties
